# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-04 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.CharField(blank=True, max_length=255)),
                ('twitter_username', models.CharField(blank=True, max_length=255)),
                ('facebook_page_url', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
