# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-04 15:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.CharField(choices=[('0', 'No'), ('1', 'Yes'), ('2', 'Inaccurate/Out-of-context')], max_length=1)),
                ('created_at', models.DateTimeField()),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('quote', models.TextField()),
                ('quote_date', models.DateField(blank=True, null=True)),
                ('quote_location', models.CharField(blank=True, max_length=255)),
                ('asked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.ElectionCandidate')),
            ],
        ),
        migrations.CreateModel(
            name='VoteOnAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('voted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voted_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.QuoteAnswer')),
            ],
        ),
        migrations.CreateModel(
            name='VoteOnQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('voted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voted_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.QuoteQuestion')),
            ],
        ),
        migrations.AddField(
            model_name='quoteanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.QuoteQuestion'),
        ),
        migrations.AlterUniqueTogether(
            name='voteonquestion',
            unique_together=set([('voted_to', 'voted_by')]),
        ),
        migrations.AlterUniqueTogether(
            name='voteonanswer',
            unique_together=set([('voted_to', 'voted_by')]),
        ),
    ]
